export const quoteServices = [
  { name: "Basic KYC Only", id: "basicKYCOnly" },
  { name: "Essentials Package", id: "essentialsPackage" },
  { name: "Premium Package", id: "premiumPackage" },
  { name: "Ultimate Package", id: "ultimatePackage" },
  { name: "Additional Team Members", id: "additionalTeamMembers" },
  { name: "Advisory Service", id: "advisoryService" },
  { name: "Project Success Prep Package", id: "projectSuccessPrepPackage" },
  { name: "AMA", id: "ama" },
  { name: "Hosted Giveaway", id: "hostedGiveaway" },
  { name: "PR Package", id: "prPackage" },
  { name: "3rd Party Referral Fees/Commissions", id: "thirdPartyReferralFees" },
  { name: "CG/CMC Listing + Fast Track + Trending", id: "cgCmcListing" },
  { name: "Custom/Misc", id: "customMisc" },
  {
    name: "Announcement Visibility Boost (RT + Pinned)",
    id: "announcementVisibilityBoost",
  },
  { name: "Buy/Resell 3rd Party Service", id: "buyResellThirdPartyService" },
  { name: "Dedicated Webpage", id: "dedicatedWebpage" },
  { name: "Expediting Fee", id: "expeditingFee" },
  { name: "Interpreter Fee", id: "interpreterFee" },
  { name: "Social Media Announcement", id: "socialMediaAnnouncement" },
  { name: "Basic Audit", id: "basicAudit" },
  { name: "Advanced Audit", id: "advancedAudit" },
  { name: "Educational Thread", id: "educationalThread" },
  { name: "Shilling Service", id: "shillingService" },
  { name: "Call Channel Package", id: "callChannelPackage" },
  { name: "Influencer Support Package", id: "influencerSupportPackage" },
  { name: "KYC Info Change Fee", id: "kycInfoChangeFee" },
  { name: "Code Development", id: "codeDevelopment" },
  { name: "Staffing (Labor)", id: "staffingLabor" },
  { name: "Reddit Trending CMS", id: "redditTrendingCMS" },
  { name: "KOL Management", id: "kolManagement" },
];

export const quoteCurrencyOptions = [
  { label: "USD", value: "USD" },
  { label: "ETH", value: "ETH" },
  { label: "BNB", value: "BNB" },
  { label: "SOL", value: "SOL" },
];
